# Generated by Django 5.1.2 on 2024-11-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('numPersonas', models.CharField(max_length=3)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(max_length=50)),
                ('nota', models.CharField(max_length=200)),
                ('acceso', models.CharField(max_length=100)),
            ],
        ),
    ]
