# Generated by Django 5.1.2 on 2024-11-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appF', '0002_alter_reserv_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
