# Generated by Django 5.1.2 on 2024-11-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appF', '0005_reserv_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='hora',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
