# Generated by Django 5.1.2 on 2024-11-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appF', '0006_alter_reserv_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='hora',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
